### ISSUE TITLE
dxcam no module named 'comtypes'

### ISSUE THREAD

**Issue by usagi123** [Franklin-Zhang0/Yolo-v8-Apex-Aim-assist#22]
I have followed [this repo](https://github.com/Chalkeys/Yolov8-Apex-Aim-assist-with-IFF) and do verify installation & check version but when I start to run. It returns me with missing the 'comtypes' module for dxcam? 
```
(yolov8) D:\Projects\Yolo-v8-Apex-Aim-assist>python main.py
Traceback (most recent call last):
  File "D:\Projects\Yolo-v8-Apex-Aim-assist\main.py", line 2, in <module>
    from screenshots import *
  File "D:\Projects\Yolo-v8-Apex-Aim-assist\screenshots.py", line 1, in <module>
    import utils.dxshot as dxcam
  File "D:\Projects\Yolo-v8-Apex-Aim-assist\utils\dxshot.py", line 3, in <module dxshot>
  File "D:\Projects\Yolo-v8-Apex-Aim-assist\utils\dxcam\__init__.py", line 3, in <module dxcam>
  File "D:\Projects\Yolo-v8-Apex-Aim-assist\utils\dxcam\dxcam.py", line 5, in <module dxcam.dxcam>
ModuleNotFoundError: No module named 'comtypes'
```

When looking for past commits, I saw you removed dxcam and replaced with dxshot. Then I tried to find definition of `import utils.dxshot as dxcam` and found nothing related to it so I am not sure those 
```
dxshot.cp37-win_amd64.pyd
dxshot.cp38-win_amd64.pyd
dxshot.cp39-win_amd64.pyd
dxshot.cp310-win_amd64.pyd
dxshot.cp311-win_amd64.pyd
```
has any relation to your `import utils.dxshot as dxcam` at all?

Did I do something wrong here?

**Comment by aksjondla** [comment]
pip install comtypes

**Comment by ghost** [comment]
Based on my solution, I change the import utils.dxshot as dxcam become import dxcam. Not sure is it work for you. and using this "pip install comtypes"
