### ISSUE TITLE
我运行成功但并没有瞄准

### ISSUE THREAD

**Issue by iu6888** [Franklin-Zhang0/Yolo-v8-Apex-Aim-assist#9]
我已经成功运行显示Main Start但没有截图框并且无法瞄准

**Comment by Franklin-Zhang0** [comment]
该程序不会显示截图框，只有在你长按鼠标左键或右键的时候才会瞄准，并且默认只检测屏幕中心1/2的区域，你可以先在游戏外使用一些apex图片测试，鼠标应该会自动移动到图片中的人物上，如果游戏外可以，游戏内不行，你可以试试把游戏调成无边框模式。如果游戏外也不行，你可以截图一下控制台我看看。

**Comment by iu6888** [comment]
在控制台界面鼠标会卡，进到游戏就变正常
![Uploading 3ce18d9cc41a1762db34cfe2e048e83.png…]()

**Comment by iu6888** [comment]
![Uploading 3ce18d9cc41a1762db34cfe2e048e83.png…]()

**Comment by Franklin-Zhang0** [comment]
<img width="410" alt="屏幕截图" src="https://user-images.githubusercontent.com/45329654/235300831-1f2754b8-e97b-43a5-937e-a9443ccf87c7.png">
我看不到你上传的图片，请在评论栏的左下角点击attach files by dragging....来上传图片

**Comment by iu6888** [comment]
我的显卡是3060t安装玩torch在游戏可以使用了但是控制台fps只有10-20左右，瞄准假人经常过头，无法跟着运动假人，我要如何解决

**Comment by Franklin-Zhang0** [comment]
应该是推理速度不足，你可以尝试安装tensorRT环境并转换trt模型来加速推理，可以参考这个fork [repo](https://github.com/Chalkeys/Yolov8-Apex-Aim-assist-with-IFF)，写得很详细

**Comment by iu6888** [comment]
我不知道我是否成功安装tensort，但也无法自动瞄准假人

**Comment by Franklin-Zhang0** [comment]
.pt模型是不需要tensorRT的，但是识别帧率较低。tensorRT安装好了之后还需要把.pt模型转化成.trt模型，并在args.py里面修改model为对应的.trt模型才能起效。

**Comment by iu6888** [comment]
我要怎么做

**Comment by Franklin-Zhang0** [comment]
转化模型的方法请看我上面发的repo，里面都有写。修改模型也仅仅只需要将args.py里面的model参数从原来默认的"apex_8n.pt"改为你转换出来的模型名字就行了。

**Comment by iu6888** [comment]
Traceback (most recent call last):
  File "D:\zm\Yolo-v8-Apex-Aim-assist-master\Yolo-v8-Apex-Aim-assist-master\main.py", line 64, in <module>
    boxes = predict_trt(args,img)
  File "D:\zm\Yolo-v8-Apex-Aim-assist-master\Yolo-v8-Apex-Aim-assist-master\trt.py", line 48, in predict_trt
    boxes = pred.inference(img, conf=args.conf, end2end=True)
  File "D:\zm\Yolo-v8-Apex-Aim-assist-master\Yolo-v8-Apex-Aim-assist-master\utils\utils.py", line 109, in inference
    num, final_boxes, final_scores, final_cls_inds = data
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by Franklin-Zhang0** [comment]
你在转换模型的时候有没有输入--end2end 参数，没有的话，可能导致这个情况。
转换的代码应该类似：
```
python export.py -o yolov8n.onnx -e yolov8n.trt --end2end --v8
```
其中，yolov8n.onnx和yolov8n.trt的文件名需要按照你转换的模型相应改变。
转化好之后，不要忘了把转化好的模型复制过去，替换原来的trt模型。
如果这些操作都是正确的，我也不知道导致的原因了。

**Comment by iu6888** [comment]
我输入并未给我trt文件只给了一个onnx文件

**Comment by Franklin-Zhang0** [comment]
onnx文件没法用于预测，要么使用原始.pt，要么转化成.trt

**Comment by fatinghenji** [comment]
同样遇到严重的性能问题。在 4070ti 上游戏内仅有 10fps。猜测是使用 cpu 在推理。我在执行模型转换的时候 yolo 提示需要让我增添参数：`device=0`来确保使用的是 gpu。请问在执行 `main.py` 时是否需要传递参数？

**Comment by Franklin-Zhang0** [comment]
不需要传递参数，trt模型无法使用cpu推理，只能使用gpu。如果使用pt模型推理，只要安装了cuda版本的pytorch，就会默认自动调用gpu。
这种性能问题通常是由于游戏占用了过多gpu资源导致，有两类解决办法。
1. 限制游戏gpu使用量
       你可以在英伟达控制面板中限制游戏帧数，或者在游戏内开启垂直同步，降低游戏画质，让游戏以无边框窗口模式运行等等。
2. 选择gpu消耗较小的模型
       选择8n模型，使用trt，fp16，int8量化等等

**Comment by fatinghenji** [comment]
限制帧数后问题解决。

**Comment by jjjkkk688** [comment]
我的也是这样，有输出listener start
Main start
Start detection:  True
Start detection:  True
Start detection:  False
但是没有瞄准

**Comment by 1109507252** [comment]
> 转化模型的方法请看我上面发的repo，里面都有写。修改模型也仅仅只需要将args.py里面的model参数从原来默认的"apex_8n.pt"改为你转换出来的模型名字就行了。

不知道为什么不能把onnx转换成trt。转换的时候没有输出

**Comment by f348564110** [comment]
您好，在您提到的repo里需要安装pycuda，但是使用pip install pycuda的话会显示版本不对的问题。请问您使用的pycuda和对应的cuda是什么版本的？
